# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
baseurl:
# It will redirect your site to this url
url                 : https://zoharyip.club
title               : Zohar's blog
name                : zohar's blog
subtitle            : "Chinese by birth, Programmer by choice"
description         : "The personal blog of zohar, a ascetic on the road to programming."
repository          : zoharyips/zoharyips.github.io
keywords            : zohar, zohar Yip, Zohar' Blog, å¶å“è±ª, zohar_Yip, zoharyips, åšå®¢, Java, å¼€å‘
date_format         : "ordinal"
timezone            : Asia/Shanghai
encoding            : "utf-8"
side_bar_repo_limit : 3

author              : zohar
github_username     : zoharyips
location            : Guangzhou, China
email               : zoharyips@outlook.com

markdown            : kramdown
kramdown:
  input             : GFM
  syntax_highlighter_opts:
    disable: true
# highlighter         : rouge
paginate            : 12
lsi                 : false
quiet               : false
future              : true
excerpt_separator   : "\n\n"                # æ‘˜å½•çš„åˆ†éš”ç¬¦
permalink           : /posts/:title.html    # åšæ–‡å‘å¸ƒçš„ URLï¼Œä¼ªé™æ€
plugins:
  - jekyll-paginate                         # åˆ†é¡µ
  - jekyll-feed                             # è‡ªåŠ¨ç”Ÿæˆ SSR æº
  - jekyll-sitemap                          # è‡ªåŠ¨ç”Ÿæˆ sitemap
  - jekyll-seo-tag                          # è‡ªåŠ¨ SEO å¤´ä¿¡æ¯ç”Ÿæˆ

collections:
  wiki:
    output          : true
    permalink       : /wiki/:path.html
  design-pattern: 
    output          : true
    permalink       : /design-pattern/:path.html
  alogrithm:
    output          : true
    permalink       : /alogrithm/:path.html
  source-code:
    output          : true
    permalink       : /source-code/:path.html
  architecture:
    output          : true
    permalink       : /architecture/:path.html
  os:
    output          : true
    permalink       : /os/:path.html


# å¯¼èˆª
navs:
  -
    href            : /
    label           : ğŸ  é¦–é¡µ

  -
    href            : /categories
    label           : ğŸ“š åˆ†ç±»

  -
    label           : ğŸ¹ æ¢ç´¢
    sub-navs:
    -
      href          : /algorithm
      label         : ğŸ“Š ç®—æ³•
    -
      href          : /design-pattern
      label         : âš–ï¸ è®¾è®¡æ¨¡å¼
    -
      href          : /source-code
      label         : ğŸ”£ æºç 
    -
      href          : /os
      label         : ğŸ–¥ï¸ æ“ä½œç³»ç»Ÿ
    -
      href          : /architecture
      label         : ğŸ“ æ¶æ„

  -
    href            : /wiki
    label           : ğŸ“ Wiki

  -
    href            : /question
    label           : ğŸ•µï¸ è¿½é—®

  -
    href            : /about
    label           : ğŸ˜€ å…³äº

subscribe_rss       : /feed.xml

# ç«™å†…æœç´¢
simple_jekyll_search:
  fulltext          : false

# leanCloud è®¿é—®ç»Ÿè®¡
leancloud:
  enable: true
  app_id: 7EiyLoiTRMpJGKx5Jyy6FV0S-gzGzoHsz
  app_key: 0l02blBLDj6noCkLMoF76LD8
  data_class_name: visited_times
  ip_class_name: visiting_ip

# è°·æ­Œåˆ†æ
google:
  analytics_id      : UA-146513129-1

# å¤‡æ¡ˆå·
beian               : ç²¤ICPå¤‡18146252å·-1
MIIT                : http://www.beian.miit.gov.cn